### ISSUE TITLE
File without license headers

### ISSUE THREAD

**Issue by puntogil** [arquillian/arquillian-core#100]
Hi
The following source file is without license headers:
./testng/core/src/main/java/org/jboss/arquillian/testng/TestDataProviderTransformer.java
Please, add license header
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance
Regards

**Comment by puntogil** [comment]
Sorry for the noise
also these one are unlicensed:
./testng/container/src/test/java/org/jboss/arquillian/testng/container/ShouldProvideConfigurationFailureToTestRunner.java
./testng/container/src/test/java/org/jboss/arquillian/testng/container/ShouldProvideVariousTestResultsToTestRunner.java

**Comment by aslakknutsen** [comment]
They are not unlicensed; https://github.com/arquillian/arquillian-core/blob/master/LICENSE

**Comment by puntogil** [comment]
yes, i know. but For Fedora this is an issue

**Comment by puntogil** [comment]
Sorry for the moise found also these file without license headers:
./build/ide/eclipse/templates/junit/ArquillianJUnitTest.java
./build/ide/netbeans/templates/JUnit/ArquillianJUnitTest.java
./container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/enricher/resource/RemoteResourceCommand.java
./container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/enricher/resource/RemoteResourceCommandObserver.java
./core/impl-base/src/main/java/org/jboss/arquillian/core/impl/threading/ThreadedExecutorService.java
./core/impl-base/src/test/java/org/jboss/arquillian/core/impl/ThreadedExecutorServiceTestCase.java
./core/impl-base/src/test/java/org/jboss/arquillian/core/impl/loadable/util/FakeService.java
./core/impl-base/src/test/java/org/jboss/arquillian/core/impl/loadable/util/ShouldBeExcluded.java
./core/impl-base/src/test/java/org/jboss/arquillian/core/impl/loadable/util/ShouldBeIncluded.java
./javadoc/stylesheet.css
./junit/core/src/main/java/org/jboss/arquillian/junit/event/AfterRules.java
./junit/core/src/main/java/org/jboss/arquillian/junit/event/BeforeRules.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/AbstractRuleStatementEnrichment.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/InnerRuleInnerStatementEnrichment.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/OuterRuleInnerStatementEnrichment.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/OuterRuleOuterStatementEnrichment.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/ResourcesImpl.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/ResourcesProvider.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/RulesEnrichmentTestCase.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/TestingMethodRule.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/TestingMethodRuleInnerStatement.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/TestingStatement.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/TestingTestRule.java
./junit/core/src/test/java/org/jboss/arquillian/junit/rules/TestingTestRuleInnerStatement.java
./junit/standalone/src/main/java/org/jboss/arquillian/junit/standalone/AllLifecycleEventExecutor.java

./protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/arq514hack/descriptors/api/web/WebAppDescriptor.java
./testenrichers/cdi/src/main/java/org/jboss/arquillian/testenricher/cdi/container/CDIExtension.java
./testenrichers/cdi/src/test/java/org/jboss/arquillian/testenricher/cdi/CDIInjectionEnricherTestCase.java
./testenrichers/cdi/src/test/java/org/jboss/arquillian/testenricher/cdi/beans/Cat.java
./testenrichers/cdi/src/test/java/org/jboss/arquillian/testenricher/cdi/beans/CatService.java
./testenrichers/cdi/src/test/java/org/jboss/arquillian/testenricher/cdi/beans/Dog.java
./testenrichers/cdi/src/test/java/org/jboss/arquillian/testenricher/cdi/beans/DogService.java
./testenrichers/cdi/src/test/java/org/jboss/arquillian/testenricher/cdi/beans/Service.java
./testenrichers/resource/src/test/java/org/jboss/arquillian/testenricher/resource/ResourceInjectionEnricherTestCase.java

thanks in advance
regards
