### ISSUE TITLE
testng 6.9.12+

### ISSUE THREAD

**Issue by puntogil** [arquillian/arquillian-core#117]
hi
any plan for update testng to 6.9.12 or major?
thanks in advance
regards

**Comment by puntogil** [comment]
There is still a problem 
/testng/core/src/test/java/org/jboss/arquillian/testng/TestNGTestBaseClass.java:[211,36] incompatible types: java.lang.String cannot be converted to org.testng.xml.XmlSuite.FailurePolicy

**Comment by bartoszmajsak** [comment]
Can you share `mvn --version` output?

**Comment by puntogil** [comment]
from http://koji.fedoraproject.org/koji/watchlogs?taskID=16403850
maven 3.4.0-0.2.20160807git9f2452a

**Comment by puntogil** [comment]
the problem is testng 6.9.12

**Comment by puntogil** [comment]
because on my system i use testng 6.9.10 and maven 3.3.9

**Comment by bartoszmajsak** [comment]
I see. We updated to 6.9.10 because of https://github.com/cbeust/testng/issues/1168
Unless this is fixed I guess it's risky to go higher.

**Comment by puntogil** [comment]
I dont know if is correct but seem 6.9.12 is not involved

**Comment by bartoszmajsak** [comment]
Is it crucial for you to have 6.9.12? Maybe we wait until they ship new release?

**Comment by puntogil** [comment]
no, i remove the arquillian-testng-core test suite from the build ...
thanks and sorry for the noise

**Comment by bartoszmajsak** [comment]
It's fine, no noise. Thanks for your feedback! We will update TestNG to the newest one when they fix it. It seems this is also affecting versions prior to 6.9.10. What are you testing it for?

**Comment by puntogil** [comment]
I was trying to import tool-tracker ...

**Comment by bartoszmajsak** [comment]
@dipak-pawar there is a new release of TestNG 6.10 - can you update and verify if that works?

**Comment by dipak-pawar** [comment]
sure @bartoszmajsak

**Comment by bartoszmajsak** [comment]
Reopening as we are going to fix it in next release (see #128)

**Comment by bartoszmajsak** [comment]
There is a new version released, but not published yet to Maven Central. https://bintray.com/cbeust/maven/testng/6.12

With this I can confirm that all works fine.

We have to wait however until the new version of TestNG lands in Maven Central :(
