### ISSUE TITLE
Update arquillian-core to TestNG 6.12 (when released)

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-core#128]
##### Issue Overview
Currently arquillian-core is using testng 6.9.10. Update it to use latest testng i.e. 6.11

**Comment by bartoszmajsak** [comment]
We have it already covered by JIRA ticket, no need for duplication here.

**Comment by dipak-pawar** [comment]
I need to refer it in testng upstream, so I created it

**Comment by bartoszmajsak** [comment]
Not sure why it's required, but if so, then for meaningful traceability I would suggest to give more context in this issue.

**Comment by dipak-pawar** [comment]
this depends on cbeust/testng#1427

**Comment by bartoszmajsak** [comment]
@dipak-pawar can you comment on JIRA about the findings?

**Comment by dipak-pawar** [comment]
sure @bartoszmajsak

**Comment by dipak-pawar** [comment]
testng team accepted issue cbeust/testng#1426, merged pr cbeust/testng#1432. Now waiting to release new version of testng.

**Comment by bartoszmajsak** [comment]
There is a new version released, but not published yet to Maven Central. https://bintray.com/cbeust/maven/testng/6.12

With this I can confirm that all works fine.
