### ISSUE TITLE
Provide Arquillian as JUnit Rule 

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-core#145]
Looks like there is some work already did for this feature in #107. 

Step steps for this as follows:

- [x] Fix/Update failing tests
- [x] Document behavior of method scoped Field Injection
- [x] Document behavior of custom TestRule if it depends on Arquillian Rule
- [x] Refactor all changes. Try to make it abstract.
- [x] Detection of runner vs rule conflict

**Comment by MatousJobanek** [comment]
Closed via #147
