### ISSUE TITLE
Getting false positive for in container tests using new Arquillian JUnit Rule

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-core#149]
*Steps to Reproduce*
* Take a clone of https://github.com/dipak-pawar/arquillian-test-examples
* cd junit5-arquillian-rules
* Change `org.jboss.arquillian.junit:arquillian-junit-container` to 1.2.0.Final
* Run `mvn clean test`

*Expected Result*
All test should not pass.
Pass: 1, Fail: 1, Skip: 1

*Actual Result*
all tests are passing

**Comment by MatousJobanek** [comment]
closed via #150
