### ISSUE TITLE
running deploymentExportExploded= true after deploymentExportExploded = false or vice versa without mvn clean throws illegal argument exception 

### ISSUE THREAD

**Issue by urbandroid** [arquillian/arquillian-core#151]
Bug report 

Issue Overview

"Cannot export a stream file to existing directory"   after deploymentExportExploded property change.

Expected Behaviour
same as when property not changed.

Current Behaviour
java.lang.IllegalArgumentException: Cannot export a stream file to existing directory: ...

Steps To Reproduce
1. Run test with deploymentExportExploded= true
2. change deploymentExportExploded to false then run test again.

<details>
Apache Maven 3.5.0 
Java version: 1.8.0_151, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.7.0-040700-generic", arch: "amd64", family: "unix"
</details>

**Comment by dipak-pawar** [comment]
Can you share small reproducible project for this bug?

**Comment by urbandroid** [comment]
just take any exemplary arquillian project and in arquillian.xml
    <engine>
       <property name="deploymentExportPath">target/deployments</property>
       this line -> <property name="deploymentExportExploded">true</property>
    </engine>
 change  marked line accordingly.

**Comment by dipak-pawar** [comment]
This is confusing to me. It'll be good if you share your `arquillian.xml` which can reproduce bug.

**Comment by dipak-pawar** [comment]
@urbandroid Thanks for reporting this issue. I can reproduce it using following steps:

Steps To Reproduce:
* git clone https://github.com/dipak-pawar/arquillian-showcase
* `git checkout core_151`
* `cd junit5-vintage`
* `mvn clean test`
* Change `<property name="deploymentExportExploded">true</property>` to `<property name="deploymentExportExploded">false</property>` from arquillian.xml.
* `mvn test`

**Comment by dipak-pawar** [comment]
@urbandroid I have provided fix for this issue in #152. You can verify it.
