### ISSUE TITLE
Arquillian uses LGPL License

### ISSUE THREAD

**Issue by jansupol** [arquillian/arquillian-core#203]
The following files use LGPL license, rather than ASL 2.0 as the rest of the project:
 - [ServerKillProcessor](https://github.com/arquillian/arquillian-core/blob/master/container/spi/src/main/java/org/jboss/arquillian/container/spi/ServerKillProcessor.java)
- [StartClassContainers](https://github.com/arquillian/arquillian-core/blob/master/container/spi/src/main/java/org/jboss/arquillian/container/spi/event/StartClassContainers.java)
- [StopClassContainers](https://github.com/arquillian/arquillian-core/blob/master/container/spi/src/main/java/org/jboss/arquillian/container/spi/event/StopClassContainers.java)

Is it a bug, or is it intended?

**Comment by bartoszmajsak** [comment]
Thanks for reporting @jansupol. I believe it's a mistake and we should change to the correct license.

@mgencur it seems you have authored those files - do you recall any particular reason for LGPL use here instead of ASL 2.0 which is used everywhere else?

**Comment by mgencur** [comment]
I think right now there's no particular reason to keep LGPL and I think at the time of creating these files LGPL was chosen because other files used the same license.

**Comment by bartoszmajsak** [comment]
It seems to me it was copy-paste error, as this commit with license headers predates files mentioned in the issue https://github.com/arquillian/arquillian-core/commit/b76366ee1c7b3442cf797651f9edddf8a5e8f22b#diff-c1e63ae7cdc5e76722ed36ed024ab454R7

I will figure out if there are any additional steps needed on our side to change those headers.

**Comment by bartoszmajsak** [comment]
Thanks for reporting @jansupol. It has been fixed now.
