### ISSUE TITLE
Maven central does not allow HTTP as of January 15, 2020

### ISSUE THREAD

**Issue by fmhwong** [arquillian/arquillian-core#228]
##### Issue Overview
Maven Central does not allow HTTP connection starting January 15, 2020.  See https://support.sonatype.com/hc/en-us/articles/360041287334

`arquillian-core 1.5.0.Final` is still picking up 
` <version.shrinkwrap_resolver>2.2.6</version.shrinkwrap_resolver>`

I think their 3.0 version has switched to HTTPS.

##### Expected Behaviour
Use HTTPS to connect to Maven Central

##### Current Behaviour
Use HTTP to connect to Maven Central

##### Steps To Reproduce
1. [step 1]
2. [step 2]

**Comment by pavolloffay** [comment]
This issue is causing failing TCK in MicroProfile projects. Can we get the fix soon and release a new version?

**Comment by pavolloffay** [comment]
cc) @bartoszmajsak

**Comment by bartoszmajsak** [comment]
As an intermediate fix, you can try to overwrite resolver version in your `pom.xml` and set it to the latest release `3.1.4`.

I will cut the release today.

**Comment by pavolloffay** [comment]
thanks @bartoszmajsak
