### ISSUE TITLE
Arquillian is not compatible with TestNG 7.x

### ISSUE THREAD

**Issue by orange-buffalo** [arquillian/arquillian-core#231]
##### Issue Overview

Arquillian is not compatible with TestNG 7.x

##### Expected Behaviour

Test is executed successfully.

##### Current Behaviour

Exception is thrown:
```
java.lang.NoSuchMethodError: org.testng.ITestNGMethod.getMethod()Ljava/lang/reflect/Method;

	at org.jboss.arquillian.testng.Arquillian$2.getMethod(Arquillian.java:213)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:129)
	at org.jboss.arquillian.testng.Arquillian.run(Arquillian.java:164)
```

##### Steps To Reproduce
Precondition: any Aruqillian test executing successfully with TestNG 6.x.
1. Upgrade TestNG to the latest 7.x.
2. Execute the test again.

**Comment by bartoszmajsak** [comment]
Thanks for reporting this issue. I believe TestNG 7.x changed quite a bit, so we most likely need to write a new adapter for it. That said - would you be interested in contributing that?

**Comment by orange-buffalo** [comment]
@bartoszmajsak, I prepared a naive implementation of TestNG 7 support, please see #232. If Arquillian team would like to go with a more sophisticated solution (like extracting common non-affected by API changes parts), please feel free to update the request / discard and re-implement it.

**Comment by bartoszmajsak** [comment]
@orange-buffalo awesome, many thanks! I will review that over the weekend!
