### ISSUE TITLE
Arquillian, CDI 2.0 and JUnit 5/Jupiter

### ISSUE THREAD

**Issue by otaviojava** [arquillian/arquillian-core#233]
Hello, I put the question in the StackOverflow and body answer it.
I guess the answer is no.
With CDI 2.0 we can improve that integration in several ways. 
I would like to make it happens.

What do you think?
If that makes sense, where is the right project to put CDI and Jupiter extension?

https://stackoverflow.com/questions/60063537/arquillian-cdi-2-0-and-junit-5-jupiter

**Comment by bartoszmajsak** [comment]
Hi @otaviojava, there's been great groundwork done by @zforgo - see https://github.com/arquillian/arquillian-core/issues/137#issuecomment-536316718

Do you think you could collaborate on that? I would be thrilled to see that happening. And also I can help to move this forward.

**Comment by hantsy** [comment]
This issue should be fixed.

**Comment by hantsy** [comment]
I have created a starter template project to demo config for Glassfish, Payara, WildFLy, OpenLiberty, and Apache TomEE, it used Arquillian 1.7.0.x and JUnit 5.

see: https://github.com/hantsy/jakartaee9-starter-boilerplate

**Comment by starksm64** [comment]
Let's open more specific issues on the current Junit 5 and CDI support as this does seem addressed at this point.
