### ISSUE TITLE
Arq. servlet protocol and Jakarta EE 9

### ISSUE THREAD

**Issue by manovotn** [arquillian/arquillian-core#248]
I recently started trying out Weld servlet with Jakarta EE 9 since there is now a Tomcat version for it.
See [this related JIRA](https://issues.redhat.com/browse/WELD-2630) issue.

In that I figured that we are still using some Arq. to perform the testing, namely Arq. servlet protocol.
[These bits](https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/runner/ServletTestRunner.java#L27-L29) are still outdated and use `javax` namespace which then causes failures (CNFE) during bootstrap.

Quick-scanning the code, I think we just need to swap [this](https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet/pom.xml#L60-L66) dependency and then change the namespaces accordingly within any related classes. But I have yet to try that (on it now).

However, I am not quite sure how we want to approach this with Arq. - whether we just update the core, or whether you want a separate EE 9 module for this. WDYT @bartoszmajsak?

FYI @starksm64

**Comment by manovotn** [comment]
Linked a PR that shows what's needed to change it, with those bits I can get Weld tests on Tomcat to execute.

**Comment by manovotn** [comment]
Note - looks like we are also going to need new version for [Tomcat embedded adapter](https://github.com/arquillian/arquillian-container-tomcat) (and later on jetty and maybe others) since those use CDI test enrichers with `javax` namespaces.

**Comment by bartoszmajsak** [comment]
Thanks for looking at this @manovotn. Much appreciated. I think we can follow the same reasoning as with #238 so I would suggest making new module `servlet-jakarta`.

**Comment by bartoszmajsak** [comment]
> Note - looks like we are also going to need new version for [Tomcat embedded adapter](https://github.com/arquillian/arquillian-container-tomcat) (and later on jetty and maybe others) since those use CDI test enrichers with `javax` namespaces.

Do you have a feeling if that's only about package rename or the changes might be bigger?

**Comment by manovotn** [comment]
@bartoszmajsak I have just created https://github.com/arquillian/arquillian-container-tomcat/issues/86 where I tried to sum it up.

It should all (99%) spin off the package name change - the Tomcat (and subsequently jetty) adapters will need to consume these newly created jakarta servlet and CDI test enrichers. With that it should work. I am trying to put the pieces together in snapshot versions right now but it's tedious job which spins across one too many projects ;-)

**Comment by bartoszmajsak** [comment]
If you need some help just let me know and I can do some boring stuff ;)

**Comment by manovotn** [comment]
> Much appreciated. I think we can follow the same reasoning as with #238 so I would suggest making new module servlet-jakarta.

Fair enough, but this might spin off the need to create some additional modules.
E.g. any other arq. project that needs to consume servlet will then need to have its `jakarta` version. Looking at servlet testing setup we now have, this shouldn't be an issue, because the dependency seems to be brought in by the tomcat adapter. But this might show up as an issue elsewhere later. But so long as we can spin up more releases when needed, we should be good.

I will try to raise a PR with that tomorrow.

> If you need some help just let me know and I can do some boring stuff ;)

Thanks, I'll keep that in mind :)
