### ISSUE TITLE
arquillian-testng.jar does not include jcommander when using TestNG 7

### ISSUE THREAD

**Issue by Zlika** [arquillian/arquillian-core#258]
##### Issue Overview

#232 adds support for TestNG 7.
When using arquillian 1.7.0.Alpha2 with TestNG 7.1.0 and wildfly 9.0.2 I have the following error when running my integration tests:

> 15:50:50,864 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /MyClassIT/ArquillianServletRunner: java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
> at org.jboss.arquillian.testng7.container.TestNGTestRunner.execute(TestNGTestRunner.java:41) [arquillian-testng.jar:]
> at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.executeTest(ServletTestRunner.java:159) [arquillian-protocol.jar:]
> at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.execute(ServletTestRunner.java:125) [arquillian-protocol.jar:]
> at org.jboss.arquillian.protocol.servlet.runner.ServletTestRunner.doGet(ServletTestRunner.java:89) [arquillian-protocol.jar:]
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
> at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
> at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86) [undertow-servlet-1.2.9.Final.jar:1.2.9.Final]
> (...)
> Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException from [Module "deployment.MyClassIT.war:main" from Service Module Loader]
> at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205) [jboss-modules.jar:1.4.3.Final]
> at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455) [jboss-modules.jar:1.4.3.Final]
> at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404) [jboss-modules.jar:1.4.3.Final]
> at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385) [jboss-modules.jar:1.4.3.Final]
> at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130) [jboss-modules.jar:1.4.3.Final]

I extracted the arquillian-testng.jar artifact bundled in the *IT.war generated to understand the problem.
When using TestNG 6 (arquillian is working in this scenario), the arquillian-testng.jar contains the following packages:
* bsh
* com.beust.jcommander
* com.beust.testng
* com.google.inject
* org.jboss.arquillian
* org.testng

When using TestNG 7 (arquillian is not working in this scenario), the arquillian-testng.jar contains only the following packages:
* com.google.inject
* org.jboss.arquillian
* org.testng

As you can see, when using TestNG7, all the transitive dependencies of TestNG7 (in particular jcommander) are not included in the arquillian-testng.jar artifact, which explains the ClassNotFoundException.
I don't know how/when the arquillian-testng.jar artifact is generated, but it seems that there is something broken here when using TestNG7.

**Comment by bartoszmajsak** [comment]
Have you tried adding `jcommander` dependency to your project? It's definitely something we missed, but that might be a workaround for the time being.

**Comment by Zlika** [comment]
Hi!

Adding testng as a compile time dependency seems to work around the problem (this way, testng and all its dependencies are packaged in the *IT.war artifact).

I had a look at the diff between the arquillian testng and testng7 modules. The only difference is one line in Arquillian.java:

> return testResult.getMethod().getMethod();

replaced by:

> return testResult.getMethod().getConstructorOrMethod().getMethod();

ITestNGMethod.getMethod() is deprecated and replaced by getConstructorOrMethod() since TestNG 6.0.1. It may have been simpler to not duplicate the testng modules and just reflectively test if the getMethod() exists or not to call the good method.
