### ISSUE TITLE
Arquillian with JUnit 5 doesn't allow (package-) private tests

### ISSUE THREAD

**Issue by Thihup** [arquillian/arquillian-core#287]
One of the features of JUnit 5 is being able to create tests without needing to specify the visibility of a test [1].
However, the Arquillian extension cannot run tests that aren't public.
Should this be fixed or add some documentation saying that is not possible?

[1] https://junit.org/junit5/docs/current/user-guide/#writing-tests

**Comment by bartoszmajsak** [comment]
Thanks for reporting. Do you think you could try to figure out the fix for it?
