### ISSUE TITLE
arquillian-junit5 runs @BeforeEach / @AfterEach code on client and server side in Container mode

### ISSUE THREAD

**Issue by kifj** [arquillian/arquillian-core#288]
##### Issue Overview

Converting tests to arquillian-junit5-container (version 1.7.0.Alpha5), I have the issue that the setup / teardown methods ( BeforeEach / AfterEach annotations) are executed twice when running tests in the container. 

One call is executed on the client, one call is executed on the server side. Tests with Junit 4 (arquillian-junit-container) ran these methods on the container side only. 

##### Expected Behaviour

BeforeEach / AfterEach are only executed once, and when the tests are run in container the execution must be on the server side. This was the behavior with Junit4, and for me the only useful way.  

##### Current Behaviour

The client side execution of these methods breaks the dependencies (because the code expects some runtime dependencies to be provided by the container). This causes exceptions which prevents the server side to be executed (which would be successful)

##### Steps To Reproduce
1. See attached project for example code

2. Define an In-Container Test with Junit 5 like below

3. if you run it, you will notice that the setup() is called on the client side and the server side. On the client side the injected @ArquillianResource is null, on the server side it is set. The JaxRS Client can not be instantiated on the client side without adding resteasy-client dependencies to the test, because the implementation is provided on the server side.

```
@ExtendWith(ArquillianExtension.class)
public class InContainerJunit5Test {
  private static final Logger LOG = LoggerFactory.getLogger(InContainerJunit5Test.class);
  
  @Deployment
  public static Archive<?> createTestArchive() {
    return ShrinkWrap.create(WebArchive.class, "arquillian-test.war").addPackages(true, "x1.wildfly.arquillian")
        .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
  }

  private String baseUrl;
  private Client client;
  private String expectedClientName;
  
  @ArquillianResource
  private URL url;
  
  @BeforeEach
  public void setup() {
    // this runs on client side now and on server side
    expectedClientName = System.getProperty("client.name", "Nobody");
    LOG.info("My name is '{}.'", expectedClientName);
    
    client = ClientBuilder.newClient();
  }
  
  @AfterEach
  public void teardown() {
    client.close();
  }
  
  @Test
  public void testResource() {
    ...
  }
```

##### Additional Information

Attached is a sample project containing a test with Junit4 and Junit5, which I deploy on Wildfly 21. If you have a running server instance, you can execute the tests with

```mvn -Pwildfly-managed -Djboss.home=/opt/wildfly-21.0.0.Final verify -Dclient.name=$USER```

Please excuse if this sample project is not completely self-contained, but I did not have much time yet. If you require it to reproduce the behavior, I will try to clean it up and upload it to github.

**Comment by kifj** [comment]
[arquillian-test.tar.gz](https://github.com/arquillian/arquillian-core/files/5540501/arquillian-test.tar.gz)

**Comment by lprimak** [comment]
Same issue exists in JUnit 4 container.
Can you verify that this fix also fixes it?
thank you

**Comment by kifj** [comment]
Hi @lprimak, thanks for supporting my PR.

In my existing JUnit4 tests this did not occur. I just verified:
- in arquillian 1.6.0 and 1.7.0.Alpha6
- using arquillian-junit-container and junit-vintage-engine 
- and Junit4 tests 
- running in container on wildfly 
that there is no execution of @Before and @After on the client side.

If this would happen, my tests would have been broken like they were with Junit5 (because of class loading dependencies which only the container can fulfill).

I'm not sure if you have seen an issue that I didn't. Have you an example for me?

**Comment by lprimak** [comment]
Definitely happening, I am seeing this in MP-TCK running against Payara, but that's not a simple example.
I will get something going soon

**Comment by lprimak** [comment]
@kifj You are correct. I can confirm that JUnit 4 is running correctly.
The MP-TCK issues are because `@Before/After/Class` runs on the client (historically I guess)
