### ISSUE TITLE
arquillian-junit5: What are required migration steps/Not injected EJB and CDI when test is in @BeforeEach method

### ISSUE THREAD

**Issue by rimuln** [arquillian/arquillian-core#293]
Is there some article/comment how migrate from old to new.

We have now IT that use base class anotated with:
```
@RunWith(Arquillian.class)
@ArquillianSuiteDeployment
@Transactional(TransactionMode.ROLLBACK)
public abstract class ArquillianBasedTest
```
and all IT tests extends it.
and in pom we are using 
```
    <dependency>
      <groupId>org.jboss.arquillian.junit</groupId>
      <artifactId>arquillian-junit-container</artifactId>
      <scope>test</scope>
    </dependency>
```

during run maven-failsafe-plugin we have set usage of surefire-junit47 because with vintage is started for each Test class new WF and it takes lot of time.
=> I expected 
change to @ExtendWith(ArquillianExtension.class)
change to dep to org.jboss.arquillian.junit5:arquillian-junit5-container
remove the surefire-junit47 as dependency for maven-failsafe-plugin.

result is
=> that WF isn't started and failed on NPE (due our call that there isn't injected some class => WF didn't started.

Should we have migrated test to use JUnit5 too? so it didn't works with tests annotated with JUnit4 annotations?

actual pom.xml dependencies are:
```
<dependency>
      <groupId>org.jboss.arquillian.junit5</groupId>
      <artifactId>arquillian-junit5-container</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.shrinkwrap.resolver</groupId>
      <artifactId>shrinkwrap-resolver-impl-maven</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.extension</groupId>
      <artifactId>arquillian-transaction-jta</artifactId>
      <version>${arquillian.transaction.jta.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.wildfly.arquillian</groupId>
      <artifactId>wildfly-arquillian-container-managed</artifactId>
      <version>${wildfly.arquillian.container.managed.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.eu.ingwar.tools</groupId>
      <artifactId>arquillian-suite-extension</artifactId>
      <version>${arquillian.suite.extension.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.extension</groupId>
      <artifactId>arquillian-jacoco</artifactId>
      <version>${arquillian_jacoco.version}</version>
      <scope>test</scope>
    </dependency>
```

**Comment by rimuln** [comment]
Ok I changed one test class to JUnit5 annotations. this correctly starts WF but NPE in setup method remain.
it is due 
`  @Inject
  private IAppServerPathProvider appServerPathProvider;

  public void setUp() throws Exception {
    appServerPathProvider.setServerConfigurationDirectory("src/test/resources");
    appServerPathProvider.setServerTemporaryDirectory("target/jboss_temp");
  }`

where injected is null. With old junit4 it works fine. The injection point has one implementation that is part of production code and is @ApplicationScoped.
Could be problem in some initialization?

**Comment by kifj** [comment]
You run this as an InContainer-Test - I think you hit the same problem as me in #288 
The NPE is thrown on the client, not the server?

**Comment by rimuln** [comment]
> You run this as an InContainer-Test - I think you hit the same problem as me in #288
> The NPE is thrown on the client, not the server?

Yes could be as integration tests are in our use case added to war and this war is packed with production ejb-jar into ear.

**Comment by rimuln** [comment]
I could confirm that #301 fix my problems here related not injected EJB and CDI.
Thanks a lot @kifj for fix it. I have now completly removed junit dependency from ejb project and all test are on JUnit5 and works fine.
Will wait for merge of #301 and release 1.7.0
