### ISSUE TITLE
Arquillian.xml is not convenient with maven reactor (multi-module) projects

### ISSUE THREAD

**Issue by lprimak** [arquillian/arquillian-core#295]
I am running into this problem more and more. Arquillian.xml is duplicated in a whole bunch of tests, with violates the DRY principal, is error-prone and redundant.

Is there any way to just use arquillian.xml that's at the root of a maven reactor project?
And if not, can this feature be added? Perhaps by a system property that points at a 'backup' arquillian.xml if it's not present in classpath?

**Comment by lprimak** [comment]
Quick look at the code seems that there is `arqullian.xml` *system property* to point to the file. I'll try this out. This is not documented anywhere BTW (from what I can find)

**Comment by lprimak** [comment]
Ok, the below works, just needs to be documented:

This places a 'backup' arquillian.xml into reactor project root
```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M5</version>
                    <configuration>
                        <systemPropertyVariables>
                            <arquillian.xml>${project.basedir}/arquillian.xml</arquillian.xml>
                        </systemPropertyVariables>
                    </configuration>
                </plugin>
```

**Comment by OndroMih** [comment]
I think that it would be better if there was an arquillian maven plugin that would generate the arquillian.xml file in the test classpath based on configuration in pom.xml. With that, the configuration of the plugin could be defined in the root project and inherited in child maven modules without any hacks.

**Comment by lprimak** [comment]
> I think that it would be better if there was an arquillian maven plugin

I disagree. My solution is not a 'hack' it works and doesn't require creating / maintaining a plugin.
This is a win.
