### ISSUE TITLE
JUnit 5 Method Parameter Injection

### ISSUE THREAD

**Issue by jamezp** [arquillian/arquillian-core#312]
In JUnit 5 a `ParameterResolver` was introduced to allow parameters to be passed. Arquillian also supports parameters being passed, e.g. `public void someTestMethod(@ArquillianResource URL url)`. However this fails with JUnit 5 as a `ParameterResolver` cannot be found.

An option I've tested with is having the `ArquillianExtension` implement the `ParameterResolver`. This works, but doesn't really have a good way to resolve the parameter so it takes a bad hack, likely broken, to get the value. I'm open to ideas on how we could resolve this.

The basic issue is we've got two different managed components. JUnit manages the `ParameterResolver` and Arquillian manages the `ResourceProvider`.

I'm not sure how it would work yet, but one idea I had was to some how allow injection into JUnit components. We'd need access to the `org.jboss.arquillian.core.spi.Manager`. For testing I did hack it with reflection, however for the `URL` injection which seems to be a good example the correct deployment store was not active.

Anyway if others have an idea of how this might work let's discuss.

**Comment by bartoszmajsak** [comment]
Thanks @Chavelp for sharing your workaround for the Graphene issue. I think we need to find the solution for broader use-case as well. 

@jamezp I will squeeze some time in the coming days and see if I can get something working. Did you make some progress around it since the original post?

@jomarko @mabartos are you guys using JUnit 5 with Graphene yet? I was wondering if you are facing a similar issue and might know how we can fix it in core?

**Comment by jamezp** [comment]
@bartoszmajsak I've not really had a chance to look since I filed it, sorry. He's on PTO for another week, but @jasondlee _may_ have.

**Comment by jomarko** [comment]
@bartoszmajsak hello, unfortunately no, our project is using arquillian just with junit 4.

**Comment by mabartos** [comment]
@bartoszmajsak Same as @jomarko

**Comment by olamy** [comment]
@Chavelp sounds good maybe you could contribute a PR?

**Comment by Chavelp** [comment]
Hi, Olivier.

The point is that it could not be a final solution. It's just a
workaround that makes things work, but is not efficient. I think the final
solution requires spending more time knowing the arquillian/graphene code
to look for it. I really would like to have this time and contribute, but
I'm just a developer with two little kids that just work at his company at
the beginning of the day and try to survive with two little time-eater
monsters at the end :D

**Comment by olamy** [comment]
> Hi, Olivier. The point is that it could not be a final solution. It's just a workaround that makes things work, but is not efficient. I think the final solution requires spending more time knowing the arquillian/graphene code to look for it. I really would like to have this time and contribute, but I'm just a developer with two little kids that just work at his company at the beginning of the day and try to survive with two little time-eater monsters at the end :D El mar, 15 mar 2022 a las 6:36, Olivier Lamy ***@***.***>) escribió:


hehe we all have this life 🤣
but yeah it need to be a more generic solution and not only graphene as could be useful for arquillian-jetty/tomcat etc...

**Comment by fanste** [comment]
Found another solution, which requires some more changes to the codebase. I will try to create a example repo with my changes.

- Register a JUnit `ParameterResolver` which fires a custom lifecycle event (`extends TestLifecycleEvent`) in `#supportsParameter` to be able to use arquillian internals.
- This event is handled by an observer and collects the parameters as it is normally done by `LocalTestExecuter`
- The collected parameters are cached by the `ParameterResolver` and reused by `#supportsParameter` and `#resolveParameter`

The problem here is how JUnit resolves parameters and how arquillian does it. JUnit resolves a single parameter per call while arquillian processes them all at once. This could be managed in two ways (== required changes to the codebase):

1. Change arquillian so it handles a single parameter only and return a wrapper object, which tells, if the parameter was successfully processed (even if the value is `null`) or if the parameter is not handled at all by arquillian.
2. Let arquillian still process all parameters at the same time, but do the same as in option 1 (return a wrapper object per parameter)

From a performance perspective, I think that option 2 is better, as we do not have to fire the event over and over again to have a valid in-arquillian-scope.

Finally we have to tell arquillian, that is should skip the own parameter resolution if JUnit 5 is used. Otherwise it will resolve the parameters a second time (1. via JUnit, 2. `LocalTestExecuter`).


**Quick'n'Worky code sample**
```java
public class ArquillianParameterResolver implements ParameterResolver {
	private static final Method fnGetManager;
	private static final Method fnGetAdaptor;
	
	static {
		try {
			fnGetManager = JUnitJupiterTestClassLifecycleManager.class.getDeclaredMethod("getManager", ExtensionContext.class);
			fnGetAdaptor = JUnitJupiterTestClassLifecycleManager.class.getDeclaredMethod("getAdaptor");

			fnGetManager.setAccessible(true);
			fnGetAdaptor.setAccessible(true);
		} catch (NoSuchMethodException | SecurityException e) {
			throw new RuntimeException(e);
		}
	}
	
	private static TestRunnerAdaptor _resolveAdaptor(ExtensionContext extensionContext) {
		try {
			JUnitJupiterTestClassLifecycleManager managerInstance = (JUnitJupiterTestClassLifecycleManager) fnGetManager.invoke(null, extensionContext);
			return (TestRunnerAdaptor) fnGetAdaptor.invoke(managerInstance);
		} catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
			throw new ParameterResolutionException("Unable to resolve the arquillian manager / test adaptor", e);
		}
	}

	@Override
	public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {

		final ExtensionContext.Store store = extensionContext.getStore(ExtensionContext.Namespace.create("arquillian", "testMethod")); 
		Object[] resolvedParameters = store.get("parameterCache", Object[].class);
		
		if(resolvedParameters == null) {
			final TestRunnerAdaptor adaptor = _resolveAdaptor(extensionContext);
			try {
				final ResolveParametersOfMethod event = new ResolveParametersOfMethod(extensionContext.getRequiredTestInstance(), extensionContext.getRequiredTestMethod());
				
				adaptor.fireCustomLifecycle(event);
				resolvedParameters = (event._parameters == null ? new Object[0] : event._parameters);

				store.put("parameterCache", resolvedParameters);
			} catch (Exception e) {
				throw new ParameterResolutionException("Unable to collect the method parameters using arquillian", e);
			}
		}

		return resolvedParameters.length != 0 && resolvedParameters[parameterContext.getIndex()] != null;
	}

	@Override
	public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
		final ExtensionContext.Store store = extensionContext.getStore(ExtensionContext.Namespace.create("arquillian", "testMethod")); 
		final Object[] resolvedParameters = store.get("parameterCache", Object[].class);
		
		return resolvedParameters[parameterContext.getIndex()];
	}

	public static final class ResolveParametersOfMethod extends TestLifecycleEvent {

		private Object[] _parameters;
		
		public ResolveParametersOfMethod(Object testInstance, Method testMethod) {
			super(testInstance, testMethod);
		}
		
		public void setResolvedParameters(Object[] parameters) {
			_parameters = parameters;
		}
	}
}
```

```java
public class JunitParameterResolverExtension implements LoadableExtension {

	@Override
	public void register(ExtensionBuilder builder) {
		builder.observer(ParameterResolverBridge.class);
	}
	
	public static class ParameterResolverBridge {
	    @Inject
	    private Instance<Deployment> deployment;

	    @Inject
	    private Instance<ServiceLoader> serviceLoader;
	    
		public void collectParameters(@Observes ResolveParametersOfMethod event) {
			final boolean runAsClient = RunModeUtils.isRunAsClientAndCheck(
		            this.deployment.get(),
		            event.getTestClass(),
		            event.getTestMethod());
			
			if(!runAsClient) {
				event.setResolvedParameters(null);
				return;
			}
			
			final Object[] parameters = enrichArguments(event.getTestMethod(), serviceLoader.get().all(TestEnricher.class));
			event.setResolvedParameters(parameters);
		}
		
		/**** proudly stolen from LocalTestExectuer ;) ****/
		private Object[] enrichArguments(Method method, Collection<TestEnricher> enrichers) {
			Object[] values = new Object[method.getParameterTypes().length];
			if (method.getParameterTypes().length == 0) {
				return values;
			}
			for (TestEnricher enricher : enrichers) {
				mergeValues(values, enricher.resolve(method));
			}
			return values;
		}

		private void mergeValues(Object[] values, Object[] resolvedValues) {
			if (resolvedValues == null || resolvedValues.length == 0) {
				return;
			}
			if (values.length != resolvedValues.length) {
				throw new IllegalStateException("TestEnricher resolved wrong argument count, expected " + values.length + " returned " + resolvedValues.length);
			}
			for (int i = 0; i < resolvedValues.length; i++) {
				Object resvoledValue = resolvedValues[i];
				if (resvoledValue != null && values[i] == null) {
					values[i] = resvoledValue;
				}
			}
		}
	}
}

```

**Comment by hantsy** [comment]
I think it is better that JUnit 5 itself provide an option to ignore the parameter if it is not resolved by JUnit 5 ParameterResovler.

**Comment by hantsy** [comment]
> Add a JUnit ParameterResolver that simply returns null for the own injection types (e.g. @InitalPage, @ArquillianResource, @Drone) => as it is a workaround, this could simply be a note for the test developers, in case they need method param injection.
@fanste Tried this, but it still return a null, not pass the method parameter resolving work to Arquillian.

**Comment by hantsy** [comment]
I tried Weld JUnit 5 this weekend, found they resolved the param injection with JUnit 5. 

There is a approach to differentiate the Param Inject from CDI and JUnit 5, a specific `@ExplicitParamInjection` on tests class provided to inject CDI bean in method parameter explicitly via `Qualifier`, event it is default bean,  add a `@Default`.

```java
public void testSomeThing(@Default MyService service){}
```

**Comment by jamezp** [comment]
I've attached a [reproducer](https://github.com/user-attachments/files/16563440/arquillian-parameter-injection.zip). I'll have another look at this now too based on the comments above.

**Comment by hantsy** [comment]
Hi, is this related PR resolved the `@InitialPage` parameter injection described by @fanste ?

I have tried to inject the `@InitialPage HomePageObject home` in the method here https://github.com/hantsy/jakartaee-faces-sample/blob/master/src/test/java/com/example/it/pageobject/HomePageObjectTest.java#L58.

But it failed, the exception stack is similar to this https://github.com/hantsy/jakartaee-faces-sample/actions/runs/17719851285/job/50350118019#step:5:64
