### ISSUE TITLE
Release Arquillian 1.7

### ISSUE THREAD

**Issue by Emily-Jiang** [arquillian/arquillian-core#336]
Can you release arquillian 1.7 as MicroProfile 5.0 would like to consume it to work with Jakarta EE 9? I am aware there were some updates went in for upgrading servlet to work with Jakarta EE 9. Please advise.

**Comment by starksm64** [comment]
There are 1.7.0.Alpha* release artifacts that were used by TCKs for the EE 9 testing. Arquillian is slow to produce final releases, so I would look to use the current  org.jboss.arquillian.protocol:arquillian-protocol-servlet-jakarta:1.7.0.Alpha9 for the EE 9 version of the servlet protocol handler.

**Comment by Emily-Jiang** [comment]
Thanks @starksm64 ! I have been using alpha9 locally. Thought it would be nice to have 1.7 released. Since you said it was slow to produce a release, I will check in the alpha9 to MicroProfile parent pom for now till 1.7 is out.

**Comment by bartoszmajsak** [comment]
There's one bit that makes it challenging to cut an official release yet - that's JUnit 5 support which needs more hardening.

I've just released `1.7.0.Alpha10` which should land in Maven Central later today.

**Comment by felipe-alves-moraes** [comment]
Hello, 

I was trying to run some tests with Arquillian 1.7.0.Alpha10 + Wiremock, and I notice that the `@BeforeAll` is not running, is this known? I'll try to investigate further, but I would say it's not really in shape to be put as a stable release yet.

**Comment by bartoszmajsak** [comment]
Thanks for your feedback @felipe-alves-moraes. Please go ahead and open an issue with your findings!

**Comment by arjantijms** [comment]
1.7.0 has been many years on alpha. I knows it's a kind of running joke in this community to keep everything on alpha, but I think not everyone outside gets the joke.

Maybe it's time to move on to at least beta, or just release 1.7.0 and retarget junit 5 support to 1.7.1 or 1.8.0?

**Comment by phillipross** [comment]
> 1.7.0 has been many years on alpha. I knows it's a kind of running joke in this community to keep everything on alpha, but I think not everyone outside gets the joke.
> 
> Maybe it's time to move on to at least beta, or just release 1.7.0 and retarget junit 5 support to 1.7.1 or 1.8.0?

Release and retarget junit5 makes a lot of sense to me

**Comment by lprimak** [comment]
Please release it. No need to "retarget" anything as JUnit 5 support has been fixed here: https://github.com/arquillian/arquillian-core/issues/309

It's well past time that Arquillian 1.7.0 is released.
Too many times I head "Arquillian is dead/legacy/dying/whatever" since there was no release in 3 years.

Thank you!

**Comment by starksm64** [comment]
Done.
