### ISSUE TITLE
Provide a REST protocol to be able to run tests that cannot use the servlet protocol

### ISSUE THREAD

**Issue by jhanders34** [arquillian/arquillian-core#408]
##### Issue Overview

Today arquillian has a servlet dependency in order to run a test on the application server. To test functions like CDI and RESTful Web Services that do not require servlet, this is not suitable since MicroProfile and now Core Profile in Jakarta EE 10 do not require the application server to expose servlet API and function in applications. Arquilian should provide a way to run a test on a server that does not have servlet enabled by using a RESTful Web Services resource instead.

##### Expected Behaviour

It is expected that there is a way to do http requests to an application server to run a test on the server, but not require the servlet API function to be exposed in the application server.  Each application server provider should not need to provide a REST protocol implementation where it can be done in the arquillian core.

##### Current Behaviour

The only option besides the servlet protocol today is the JMX protocol or the application server provider needs to write their own protocol.

##### Steps To Reproduce

Run the Jakarta EE 10 Core Profile TCK tests on an application server that does not use servlet to provide RESTful Web Services function.  An example implementation is Open Liberty where the servlet-6.0 feature is not in the server.xml or helidon or quarkus that doesn't have a servlet container to run the RESTful Web Services function.

##### Additional Information

https://github.com/OpenLiberty/liberty-arquillian/pull/118 provides a vendor implementation of this same code except with the io.openliberty package prefix instead of org.jboss.  Using the implementation that is provided in PR #407, the liberty arquillian tests pass.  When the PR associated with this issue is merged and a new release is created for arquillian, the liberty arquillian project will be updated to use the arquillian REST protocol implementation.

**Comment by jamezp** [comment]
Just to link it here, I've filed https://issues.redhat.com/browse/WFARQ-112 for the WildFly Arquillian Adapter.
