### ISSUE TITLE
Unable to build with -Prelease due to javadoc error

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-core#414]
##### Issue Overview

The current release build is failing if the release profile is enabled due to a javadoc error.

##### Expected Behaviour
The release builds

##### Current Behaviour
The build fails when generating the javadoc for the arquillian-core-api module:

```
1 error
[INFO] FAILURE build of project org.jboss.arquillian.core:arquillian-core-api
[INFO] Builder state: blocked=0 finished=1 ready-or-running=0 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.942 s (Wall Clock)
[INFO] Finished at: 2022-07-27T21:53:08-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:javadoc (default-cli) on project arquillian-core-api: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: warning - The old Doclet and Taglet APIs in the packages
[ERROR] com.sun.javadoc, com.sun.tools.doclets and their implementations
[ERROR] are planned to be removed in a future JDK release. These
[ERROR] components have been superseded by the new APIs in jdk.javadoc.doclet.
[ERROR] Users are strongly recommended to migrate to the new APIs.
[ERROR] javadoc: error - invalid flag: -Xdoclint:none
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/starksm/Dev/JBoss/Weld/arquillian-core/core/api/target/site/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

##### Steps To Reproduce
1. cd arquillian-core/core/api
2. mvn -Prelease compile javadoc:javadoc

##### Additional Information

```
<details>
 <summary>$mvn --version</summary>
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /usr/local/Cellar/maven/3.8.4/libexec
Java version: 11.0.16, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.5", arch: "x86_64", family: "mac"
</details>
```
I am seeing the same problem on another linux build system as well. The full output of the mvn -X command and options file passed to the javadoc command is attached in the build.log file.

[build.log](https://github.com/arquillian/arquillian-core/files/9205137/build.log)

**Comment by bartoszmajsak** [comment]
I was able to cut the release using JDK 8.

```
export VERSION=1.7.0.Alpha11 
export NEXT_VERSION=1.7.0.Final-SNAPSHOT

mvn -DreleaseVersion=$VERSION -Dtag=$VERSION -DdevelopmentVersion=$NEXT_VERSION release:prepare release:perform -Prelease 
```

It's in the staging repo - so don't worry.

Opened PR with the fixes.

**Comment by chengfang** [comment]
Are we ready to do a final release of 1.7.0, instead of Alpha? I see community request for such a final release (https://github.com/arquillian/arquillian-core/issues/336). It would also help WildFly to finalize wildfly-arquillian and use final releases in tests.

**Comment by bartoszmajsak** [comment]
> Are we ready to do a final release of 1.7.0, instead of Alpha? I see community request for such a final release (https://github.com/arquillian/arquillian-core/issues/336). It would also help WildFly to finalize wildfly-arquillian and use final releases in tests.

It depends how final is junit5 integration. I think it's still in somewhat alpha stage. The rest is rather stable in my eyes.

**Comment by jamezp** [comment]
I think a decision on #312 should be made before final. If it's Arquillian method parameter injection is no longer supported, then it could be a case where some users need to make changes before they can migrate.
