### ISSUE TITLE
Jakarta EE 10 

### ISSUE THREAD

**Issue by RzaAlbert** [arquillian/arquillian-core#444]
My REST Api were working properly(all tests passed), but recently i have done migration to Jakarta EE 10 and i think that arquillian adapters are not compatible with the new version. When i try to run the tests i get: 

java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor

My pom.xml:
<dependency>
    <groupId>org.jboss.arquillian.protocol</groupId>
    <artifactId>arquillian-protocol-servlet</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian.junit</groupId>
    <artifactId>arquillian-junit-container</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian.container</groupId>
    <artifactId>arquillian-glassfish-embedded-3.1</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.eu.ingwar.tools</groupId>
    <artifactId>arquillian-suite-extension</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian.extension</groupId>
    <artifactId>arquillian-transaction-jta</artifactId>
    <scope>test</scope>
</dependency>

**Comment by bartoszmajsak** [comment]
Can you share code snippets and errors you are getting? Or even better - a small project serving as reproducer will be great to nail down the issue.

**Comment by bvfalcon** [comment]
For arquillian.xml it needs to add protocol "Servlet 6.0" (by analog with  [Servlet 5.0](https://github.com/arquillian/arquillian-core/blob/master/protocols/servlet-jakarta/src/main/java/org/jboss/arquillian/protocol/servlet5/Servlet5Extension.java)).

**Comment by jhanders34** [comment]
For Jakarta EE 9 and 10 you will need to switch to the arquillian-protocol-servlet-jakarta or if you don't want to depend on servlet you can use arquillian-protocol-rest-jakarta.

**Comment by starksm64** [comment]
FYI, starting with the 1.8.0.Final release, the jakarta.* based modules will be in the https://github.com/arquillian/arquillian-jakarta repo and released independently from core.
