### ISSUE TITLE
Incorrect metadata for arquillian-bom-1.7.0 on maven central

### ISSUE THREAD

**Issue by haster** [arquillian/arquillian-core#475]
##### Issue Overview

The metadata for arquillian-bom-1.7.0 on maven central is incorrect. It doesn't reflect the 1.7.0.Final version being released. The "latest" and "release" versions are still on 1.7.0.Alpha14, and 1.7.0.Final is also not mentioned in the list of versions. The last updated tag is '20230204013001'. See https://repo1.maven.org/maven2/org/jboss/arquillian/arquillian-bom/maven-metadata.xml

We use the bom to import dependency management for all arquillian artifacts, and to be able to quickly upgrade them all. However, this now breaks. 

The metadata for other artifacts (such as arquillian-core-api and arquillian-config-api) is correct, which leads to the maven versions plugin saying the 1.7.0.Final version is available for those artifacts, but if we update the bom to 1.7.0.Final maven refuses to download that and everything breaks.

##### Expected Behaviour

I can import the 1.7.0.Final version of the arquillian-bom and build my project.

##### Current Behaviour

When importing the 1.7.0.Final version of the arquillian-bom, maven errors out:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.jboss.arquillian:arquillian-bom:pom:1.7.0.Final in <company repo>
```

##### Steps To Reproduce
1. Add 
```xml
<dependency>
        <groupId>org.jboss.arquillian</groupId>
        <artifactId>arquillian-bom</artifactId>
        <version>1.7.0.Final</version>
        <scope>import</scope>
        <type>pom</type>
</dependency>
```
to the dependency-management section of your pom.
2. Run `mvn package` or any other kind of maven command. 

Alternatively, look at the metadata on maven central.

##### Additional Information

**Comment by kaiwinter** [comment]
One thing I like to add is that the pom is missing here: https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.7.0.Final/

The checksums are there but the pom is not.

**Comment by hantsy** [comment]
I have encountered the same issue when upgrading to 1.7.0.Final.

**Comment by rimuln** [comment]
Same for us. We migrate now to Jakarta EE10 and WF10 and got same errors during maven builds after change Alpha14 to Final

**Comment by fhochleitner** [comment]
Hi, there seems to be still an issue. at least for my side. 

the uploaded sha1 and md5 files contain an invalid checksum. 

sha1 content: 2811ba27a71a8bda0602161ffe2f6e1429da8068
` fhochleitner@fhochleitner-gepardec ~/Downloads  $ sha1sum arquillian-bom-1.7.0.Final.pom 
36257165a0945753efb3f9d473d86c6f4c6c6f6e  arquillian-bom-1.7.0.Final.pom
`

md5content:  e861b084b44430e0cc4381c87abf8e82
` fhochleitner@fhochleitner-gepardec ~/Downloads  $ md5sum arquillian-bom-1.7.0.Final.pom
181dc239e22d3bedee8e12f18784d0b8  arquillian-bom-1.7.0.Final.pom
`
therefore builds fail on our side

**Comment by metacosm** [comment]
Still seeing issues as well: https://github.com/quarkiverse/quarkus-operator-sdk/actions/runs/5526384277/jobs/10081061245#step:8:1322
