### ISSUE TITLE
The Jakarta related dependent modules should be broken out

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-core#516]
##### Issue Overview
With the revival of the Jakarta EE specifications starting to produce new content, an issue with keeping the Arquillian modules related to the Jakarta EE APIs is that The EE APIs are updating the requirement Java SE used for compliation. EE 10 had a baseline of Java SE 11 and EE 11 will have a baseline of Java SE 21.

The problem this causes in seen in the current CI build of the #514 PR. Updating the Jakarta Rest api version to 3.1.0 has added a requirement for Java SE 11 and the Java SE 8 based tests are now failing.

What I would propose is that:
1. Create a new arquillian-jakarta repository
2. The exisitng arquillian-core repo submodules that depend on Jakarta EE apis be moved into the arquillian-jakarta repo
3. A new 1.8.0.Final release of arquillian-core is made without the arquillian-jakarta content
4. a 1.8.0.Final release of the arquillian-jakarta content is made

**Comment by jamezp** [comment]
This sounds like a good plan to me.  I think it makes sense to have the arquillian-jakarta repository and do a clean 1.8 break. We could even start requiring Java 11 for arquillian-core, but that's not critical at all.

**Comment by starksm64** [comment]
We could and probably should leave the legacy Java EE based modules in the core repo since they would probably never be touched again anyway.

**Comment by bartoszmajsak** [comment]
FWIW I created a repo for this https://github.com/arquillian/arquillian-jakarta

**Comment by starksm64** [comment]
This has been done. The first arquillian-core release to pick up this change will be the 1.8.0.Final release

**Comment by jamezp** [comment]
If needed, next week I can test local builds of the SNAPSHOT's in wildfly-arquillian. I assume they work fine, but just to test it :)
