### ISSUE TITLE
Change default project creation settings

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-core#550]
##### Issue Overview

I created a https://github.com/orgs/arquillian/projects/5 project to manage an Arquillian Core 2.0 release, but it is private and I have no ability to change that. 

##### Expected Behaviour
The default setting for Projects should be public so that they can be viewed by anyone

**Comment by bartoszmajsak** [comment]
Should work now. I'm on PTO now, so if anything admin urgent please ping @aslakknutsen .
