### ISSUE TITLE
Disable the wildfly integration tests until stabilized and reduced in scope

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-core#567]
##### Issue Overview

These tests are taking too long to run, and now are failing because there is not a 1.8.2.Final-SNAPSHOT in the jboss repo. How is that supposed to be populated from the PR?

##### Expected Behaviour
Tests should run in under a few minutes

##### Current Behaviour
The last successful run I saw was 180 mins. Now it is taking 5-6min to fails with:
```
Error:  Failed to execute goal on project wildfly-testsuite-shared: Could not resolve dependencies for project org.wildfly:wildfly-testsuite-shared:jar:33.0.0.Beta1-SNAPSHOT: The following artifacts could not be resolved: org.jboss.arquillian.container:arquillian-container-test-spi:jar:1.8.2.Final-SNAPSHOT, org.jboss.arquillian.junit:arquillian-junit-container:jar:1.8.2.Final-SNAPSHOT: Could not find artifact org.jboss.arquillian.container:arquillian-container-test-spi:jar:1.8.2.Final-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
```

**Comment by jamezp** [comment]
Where do these tests run?

**Comment by rhusar** [comment]
> Where do these tests run?

Nowhere now - this commit removed them - https://github.com/arquillian/arquillian-core/commit/5a6bf823d42898c84793d303fea2b5f2b69a5332

But they ran on normal GHA runners.

We can come up with some trimming if they are running longer than we seem reasonable.

**Comment by jamezp** [comment]
Ah, I see. Thank you @rhusar. I somehow missed that part :)

**Comment by starksm64** [comment]
The wildfly-arquillian build should be sufficient as that is all the wildfly integration tests would be exercising for the most part.

**Comment by starksm64** [comment]
Closing this as the integration-tests suffice as a replacement.
