### ISSUE TITLE
We need some unit test implementation CI testing

### ISSUE THREAD

**Issue by starksm64** [arquillian/arquillian-core#580]
##### Issue Overview
It seems like we need more unit test framework validation in the CI tests

##### Expected Behaviour
We should validate key versions of Junit 4/5 and TestNG

##### Current Behaviour
We don't have such tests

**Comment by lprimak** [comment]
Not quite sure that'll be enough. Integration testing IMHO is the only surefire way to test things.
For example, how do you test Junit 5 extensions with a unit test?

I use https://github.com/flowlogix/test-arq-suite integration test for both JUnit 5 and TestNG canary tests, and so far this simple test translated 100% to all larger projects.

**Comment by starksm64** [comment]
Yes, we need an integration-test module that is skipped during the release but run for validation.

**Comment by lprimak** [comment]
Looks like TestNG works.
Couldn't really test JUnit but it looks ok.
I think 1.9.0 release would be appreciated since 1.8.1 is broken :)

Thanks guys!
