### ISSUE TITLE
Compatility Issue with JUnit Jupiter 5.11.0

### ISSUE THREAD

**Issue by hantsy** [arquillian/arquillian-core#622]
When upgrading to junit-jupiter bom, I got an exception like:

```bash 
TestEngine with ID 'junit-jupiter' failed to discover tests
```

Check the build stack: https://github.com/hantsy/arquillian-container-glassfish-jakarta/actions/runs/10662189449/job/29548941502

**Comment by lprimak** [comment]
Also no issues here: https://github.com/flowlogix/test-arq-suite

**Comment by lprimak** [comment]
Make sure different JUnit dep versions are not mixes. I think this is the root cause of your issue

**Comment by jamezp** [comment]
@hantsy I've seen this before. If you turn on logging you might see the issue. The issues I've seen are missing dependencies so the engine fails to be created.

**Comment by hantsy** [comment]
It seems the jboss-parent and custom junit-bom conflicts, I list the dependencies, and got.


```bash 
- org.junit.jupiter:junit-jupiter:jar:5.11.0:test
[INFO]    +- org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
[INFO]    |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO]    |  +- org.junit.platform:junit-platform-commons:jar:1.11.0:test
[INFO]    |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO]    +- org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
[INFO]    \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.3:test
[INFO]       \- org.junit.platform:junit-platform-engine:jar:1.10.3:test
```

**Comment by hantsy** [comment]
And I found I added `org.junit.jupiter:junit-jupiter` version will conflict with the dependencies combined from arquillian-junit5 (`org.junit.jupiter:junit-jupiter-api`, `org.junit.jupiter:junit-jupiter-engine`, `org.junit.jupiter:junit-jupiter-params`)

**Comment by lprimak** [comment]
Basically you have two choices:
- import `junit-bom` in your application
- Use a set of exclusions / inclusions asI do in https://github.com/flowlogix/depchain/tree/main/integration-test

**Comment by lprimak** [comment]
Or you can just use below and reuse the work I've already done

```
       <dependency>
            <groupId>com.flowlogix.depchain</groupId>
            <artifactId>integration-test</artifactId>
            <version>28</version>
            <scope>test</scope>
        </dependency>
```

**Comment by hantsy** [comment]
@lprimak  Got it worked. 

I found several dependencies declared JUnit Jupiter as deps. In my `dependencyManagement`, I must move my `junit-bom` before them to resolve the version consistence issue.
