### ISSUE TITLE
ARQ-1896 Make JMX objectname configurable for JMXTestRunner and JMXMethodExecutor.

### ISSUE THREAD

**Issue by APIReader** [arquillian/arquillian-core#73]
Currently, JMXTestRunner#runTestMethod(String className, String methodName) expects to find the test class and run the test method using the classloader set in the constructor. This is a problem when my tests are expected to run inside different containers (hence different classloaders). One easy work around is to publish one JMXTestRunner per container (hence unique objectname has to be provided to avoid conflict).

**Comment by aslakknutsen** [comment]
fixed by https://github.com/arquillian/arquillian-core/commit/0e5305fb447c5e72268b3280e53b12e6d30678ca
