### ISSUE TITLE
Original exception lost when thrown from @Before-annotated method

### ISSUE THREAD

**Issue by CSchulz** [arquillian/arquillian-core#86]
I have recognized that there seems to be an issue with JUnit and Arquillian.

If there is an exception in @before-annotated method, it seems to be lost. There is no entry in the log neither the test will be aborted instantly.
```
    @Before
    public void preparePersistenceTest() {
        throw new RuntimeException("test");
```

A NPE occurs in @after-annotated method. The @test-annotated method doesn't fail fast.

Here the console output:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.979 sec <<< FAILURE! - in RelocateTest
relocateSuccessful(RelocateTest)  Time elapsed: 0.24
1 sec  <<< ERROR!
java.lang.NullPointerException: null
        at RelocateTest.clearData(PackageRelocateTest.java:77)
```

I am using Arquillian JUnit Container 1.1.8.Final and JUnit 4.11.

**Comment by CSchulz** [comment]
I think I have found the issue. testFailure is called from outside and override an existing exception https://github.com/arquillian/arquillian-core/blob/e39433696861f11588180894378c32f795da8085/junit/container/src/main/java/org/jboss/arquillian/junit/container/JUnitTestRunner.java#L110

This exception is used to create the testresult:
https://github.com/arquillian/arquillian-core/blob/e39433696861f11588180894378c32f795da8085/junit/container/src/main/java/org/jboss/arquillian/junit/container/JUnitTestRunner.java#L70

**Comment by aslakknutsen** [comment]
@CSchulz Yes, I believe you are correct. I guess we could expand on this and collect 'all' exceptions :)
