### ISSUE TITLE
Add System Environment resolution

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-core#88]
As discussed in http://discuss.arquillian.org/t/arquillian-xml-alternative-format/206/12, you can configure arquillian using properties file or system properties (`System.getProperties`). Now it has been added support for configuring arquillian from system environment properties (`System.getenv`). 

Moreover the override rules has been changed so that properties of the system has more precedence than properties of files.

So environment variables takes preference from system properties which takes preference from arquillian.properties which takes preference from arquillian.xml.

**Comment by aslakknutsen** [comment]
Core uses JIRA, created https://issues.jboss.org/browse/ARQ-1966
